apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: docker.io/vshn/crossplane-service-broker-poc
    newName: test
resources:
  - ../base
  - secret.yaml
patchesStrategicMerge:
  - deployments.yaml
